spring:
  # 어플리케이션 이름
  application:
    name: mes_boot

  # 데이터베이스 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:h2:mem:testdb}  # 기본값으로 H2 설정
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}


# 서버 포트
server:
  port: 7010
  address: 0.0.0.0 #모든 IP에서 접속 가능 하도록 설정


# MyBatis 설정
mybatis:
  mapper-locations:
    - mybatis/**/*.xml
    - mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB 컬럼명 자동 카멜케이스 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 콘솔에 쿼리 로그 출력


# openapi 설정 (swagger-ui)
springdoc:
  api-docs:
    path: /api-docs # OpenAPI 문서 경로
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로

# Swagger 자동 열기 설정
swagger:
  auto-open:
    enabled: false # false로 설정하면 자동 열기 비활성화